name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build Docker image
        run: make build

      - name: Test Docker image
        run: make test
